(() => {
  const ISSC = {service:"49535343-fe7d-4ae5-8fa9-9fafd205e455",write:"49535343-8841-43f4-a8d4-ecbe34729bb3",notify:"49535343-1e4d-4bd9-ba61-23c647249616"};
  const NUS = {service:"6e400001-b5a3-f393-e0a9-e50e24dcca9e",write:"6e400002-b5a3-f393-e0a9-e50e24dcca9e",notify:"6e400003-b5a3-f393-e0a9-e50e24dcca9e"};
  const OPTIONAL = [ISSC.service,NUS.service,"generic_access","device_information","0000ffe0-0000-1000-8000-00805f9b34fb","0000fff0-0000-1000-8000-00805f9b34fb","0000ff00-0000-1000-8000-00805f9b34fb"];
  const PREFIX = ["B3PRO","B3Pro","B3","PIVA","Piva"];
  const LS = "b3pro.ble.v3";
  const MODES = [{id:0,name:"Cực lạnh"},{id:1,name:"Tiết kiệm"},{id:2,name:"Im lặng"},{id:3,name:"Kiểm soát nhiệt"}];
  const LIGHTS = [{id:0,name:"Linh động"},{id:1,name:"Hơi thở"},{id:2,name:"Cầu vồng chạy"},{id:3,name:"Cầu vồng thở"},{id:4,name:"Trắng thở"},{id:5,name:"Xanh thở"},{id:6,name:"Xanh-trắng thở"},{id:7,name:"Đa sắc PIVA"},{id:8,name:"Xung"}];
  const CMD = {QUERY:1,POWER:2,MODE:3,LIGHT_EN:4,LIGHT_FX:5,RAGE:6,SMART:7,PROTECT:8,PID_TEMP:9};
  const state = {device:null,server:null,writeChar:null,notifyChar:null,connected:false,connecting:false,power:true,light:true,mode:0,lightFx:0,rage:false,smart:false,rpm:null,watts:null,pps:null,fw:"V212",userDisconnect:false,reconnectTries:0};
  const ble = {writeChain:Promise.resolve(),rxBuf:new Uint8Array(0),pollTimer:null,reconnectTimer:null,onDisconnectBound:null,onNotifyBound:null,renderTok:0};
  const $ = id => document.getElementById(id);
  const logEl = $("log");
  function log(msg){const t=new Date().toLocaleTimeString("vi-VN");logEl.textContent+=`[${t}] ${msg}\n`;if(logEl.textContent.length>16000)logEl.textContent=logEl.textContent.slice(-10000);logEl.scrollTop=logEl.scrollHeight;}
  function toast(msg){const el=$("toast");el.textContent=msg;el.style.display="block";clearTimeout(toast._t);toast._t=setTimeout(()=>el.style.display="none",2200);}
  const hex=buf=>[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,"0")).join(" ").toUpperCase();
  function parseHex(s){const c=s.replace(/[^0-9a-fA-F]/g,"");if(c.length%2)throw new Error("Mã HEX lẻ byte");const o=new Uint8Array(c.length/2);for(let i=0;i<o.length;i++)o[i]=parseInt(c.substr(i*2,2),16);return o;}
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function withTimeout(p,ms,label){let t;const to=new Promise((_,rej)=>{t=setTimeout(()=>rej(new Error((label||"Bluetooth")+" hết hạn "+ms+" ms")),ms);});return Promise.race([p,to]).finally(()=>clearTimeout(t));}
  function concatBytes(a,b){const o=new Uint8Array(a.length+b.length);o.set(a,0);o.set(b,a.length);return o;}
  function loadPref(){try{return JSON.parse(localStorage.getItem(LS)||"{}");}catch(e){return {};}}
  function savePref(extra){try{localStorage.setItem(LS,JSON.stringify(Object.assign(loadPref(),extra)));}catch(e){}}
  function encodeFrame(cmd,payload=[]){const codec=$("codecSel").value;const pl=payload instanceof Uint8Array?payload:Uint8Array.from(payload);if(codec==="raw"){const o=new Uint8Array(1+pl.length);o[0]=cmd;o.set(pl,1);return o;}const body=new Uint8Array(1+pl.length);body[0]=cmd;body.set(pl,1);const pkt=new Uint8Array(3+body.length+1);if(codec==="aa55"){pkt[0]=0xAA;pkt[1]=0x55;}else{pkt[0]=0xA5;pkt[1]=0x5A;}pkt[2]=body.length;pkt.set(body,3);let x=0;for(let i=2;i<pkt.length-1;i++)x=codec==="aa55"?((x+pkt[i])&255):(x^pkt[i]);pkt[pkt.length-1]=x;return pkt;}
  function pullFrames(buf){const frames=[];let i=0;while(i+4<=buf.length){const a=buf[i],b=buf[i+1];if((a===0xA5&&b===0x5A)||(a===0xAA&&b===0x55)){const end=i+3+buf[i+2]+1;if(end>buf.length)break;frames.push(buf.slice(i,end));i=end;}else i++;}return {frames,rest:buf.slice(i)};}
  function applyStatus(bytes){if(bytes.length<4)return;for(let i=0;i<bytes.length-1;i++){const le=bytes[i]|(bytes[i+1]<<8);const be=(bytes[i]<<8)|bytes[i+1];if(le>=800&&le<=9000){state.rpm=le;break;}if(be>=800&&be<=9000){state.rpm=be;break;}}for(let i=0;i<bytes.length;i++){if(bytes[i]>=5&&bytes[i]<=40){state.watts=bytes[i];break;}}scheduleRender();}
  function setBusy(on){state.connecting=on;$("btnConnect").disabled=on;$("btnScanAll").disabled=on;$("btnReconnect").disabled=on;$("connDot").classList.toggle("busy",on&&!state.connected);if(on&&!state.connected)$("connText").textContent="Đang kết nối…";}
  function scheduleRender(){if(ble.renderTok)return;ble.renderTok=requestAnimationFrame(()=>{ble.renderTok=0;render();});}
  function render(){const ok=state.connected;$("connDot").classList.toggle("ok",ok);$("connDot").classList.toggle("busy",state.connecting&&!ok);$("connText").textContent=ok?"Đã kết nối":(state.connecting?"Đang kết nối…":"Chưa kết nối");const logo=$("logoVong");if(logo)logo.classList.toggle("live",ok&&state.light);$("rpmVal").innerHTML=(state.rpm??"\u2014")+"<small>RPM</small>";$("ppsVal").textContent=state.pps??(ok?"PPS":"\u2014");$("wattVal").textContent=state.watts!=null?(state.watts+"W"):"\u2014";$("pwrToggle").classList.toggle("on",state.power);$("pwrVal").textContent=state.power?"Bật":"Tắt";$("modeLabel").textContent=MODES[state.mode].name;$("lightToggle").classList.toggle("on",state.light);$("lightLabel").textContent=state.light?LIGHTS[state.lightFx].name:"Tắt";$("rageLabel").textContent=state.rage?"Bật":"Tắt";$("smartLabel").textContent=state.smart?"Bật":"Tắt";$("fwLabel").textContent=state.fw;const r=document.querySelector('[data-sheet="rage"]');const s=document.querySelector('[data-sheet="smart"]');if(r)r.classList.toggle("active",state.rage);if(s)s.classList.toggle("active",state.smart);}
  function startPoll(){stopPoll();if(!$("autoPoll").checked)return;ble.pollTimer=setInterval(()=>{if(state.connected&&document.visibilityState==="visible")sendCmd(CMD.QUERY,[0]).catch(()=>{});},2000);}
  function stopPoll(){if(ble.pollTimer){clearInterval(ble.pollTimer);ble.pollTimer=null;}}
  const propsOf=c=>Object.keys(c.properties).filter(k=>c.properties[k]).join(",");
  function scoreW(c,prefer){let s=0;if(prefer&&c.uuid===prefer)s+=50;if(c.uuid===ISSC.write||c.uuid===NUS.write)s+=20;if(c.properties.writeWithoutResponse)s+=6;if(c.properties.write)s+=4;return s;}
  function scoreN(c,prefer){let s=0;if(prefer&&c.uuid===prefer)s+=50;if(c.uuid===ISSC.notify||c.uuid===NUS.notify)s+=20;if(c.properties.notify)s+=6;if(c.properties.indicate)s+=3;return s;}
  async function pickWrite(chars,prefer){return [...chars].sort((a,b)=>scoreW(b,prefer)-scoreW(a,prefer)).find(c=>c.properties.writeWithoutResponse||c.properties.write)||null;}
  async function pickNotify(chars,prefer){return [...chars].sort((a,b)=>scoreN(b,prefer)-scoreN(a,prefer)).find(c=>c.properties.notify||c.properties.indicate)||null;}
  async function discoverGatt(server){const wanted=[ISSC.service,NUS.service,OPTIONAL[4],OPTIONAL[5]];let services=[];for(const uuid of wanted){try{services.push(await server.getPrimaryService(uuid));}catch(e){}}if(!services.length)services=[...await server.getPrimaryServices()];log("Dịch vụ: "+services.map(s=>s.uuid).join(", "));let writeChar=null,notifyChar=null;for(const svc of services){const chars=await svc.getCharacteristics();log("  "+svc.uuid+" → "+chars.map(c=>c.uuid.slice(0,8)+"["+propsOf(c)+"]").join(" | "));const preferW=svc.uuid===ISSC.service?ISSC.write:(svc.uuid===NUS.service?NUS.write:null);const preferN=svc.uuid===ISSC.service?ISSC.notify:(svc.uuid===NUS.service?NUS.notify:null);const w=await pickWrite(chars,preferW);const n=await pickNotify(chars,preferN);if(w){writeChar=w;notifyChar=n;if(n)break;}}if(!writeChar)throw new Error("Không tìm thấy kênh ghi");return {writeChar,notifyChar};}
  async function writeChunk(char,bytes){try{if(char.properties.writeWithoutResponse){await char.writeValueWithoutResponse(bytes);return;}}catch(e){log("Ghi nhanh lỗi → ghi thường: "+e.message);}await char.writeValue(bytes);}
  function enqueueWrite(bytes){ble.writeChain=ble.writeChain.then(()=>flushWrite(bytes)).catch(e=>log("Hàng đợi gửi: "+e.message));return ble.writeChain;}
  async function flushWrite(bytes){if(!state.writeChar||!state.device?.gatt?.connected)throw new Error("Chưa kết nối");const chunk=Number($("chunkSel").value);const u=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);log("Gửi "+hex(u));if(!chunk||u.length<=chunk){await writeChunk(state.writeChar,u);return;}for(let i=0;i<u.length;i+=chunk){await writeChunk(state.writeChar,u.subarray(i,Math.min(i+chunk,u.length)));await sleep(12);}}
  const sendCmd=(cmd,payload)=>enqueueWrite(encodeFrame(cmd,payload));
  function writeRaw(bytes){if(!state.writeChar){toast("Chưa kết nối");return;}return enqueueWrite(bytes);}
  function onNotify(ev){const chunk=new Uint8Array(ev.target.value.buffer);log("Nhận "+hex(chunk));ble.rxBuf=concatBytes(ble.rxBuf,chunk);if(ble.rxBuf.length>1024)ble.rxBuf=ble.rxBuf.slice(-256);const {frames,rest}=pullFrames(ble.rxBuf);ble.rxBuf=rest;if(frames.length)frames.forEach(applyStatus);else applyStatus(chunk);}
  function hookDisconnect(device){if(ble.onDisconnectBound&&state.device){try{state.device.removeEventListener("gattserverdisconnected",ble.onDisconnectBound);}catch(e){}}ble.onDisconnectBound=()=>{const wasUser=state.userDisconnect;log("Mất liên kết GATT");teardownLink();scheduleRender();if(!wasUser&&$("autoReconnect").checked)scheduleReconnect();else toast("Đã ngắt kết nối");};device.addEventListener("gattserverdisconnected",ble.onDisconnectBound);}
  function teardownLink(){stopPoll();if(ble.reconnectTimer){clearTimeout(ble.reconnectTimer);ble.reconnectTimer=null;}if(state.notifyChar&&ble.onNotifyBound){try{state.notifyChar.removeEventListener("characteristicvaluechanged",ble.onNotifyBound);}catch(e){}}state.connected=false;state.connecting=false;state.writeChar=null;state.notifyChar=null;state.server=null;ble.rxBuf=new Uint8Array(0);}
  function scheduleReconnect(){if(state.userDisconnect||!state.device)return;const n=Math.min(state.reconnectTries+1,6);state.reconnectTries=n;const wait=Math.min(8000,400*(2**(n-1)));log("Sẽ kết nối lại sau "+wait+" ms (lần "+n+")");$("connText").textContent="Mất máy · thử lại…";ble.reconnectTimer=setTimeout(()=>attach(state.device,{silent:true}).catch(e=>{log("Kết nối lại lỗi: "+e.message);if(n<6)scheduleReconnect();}),wait);}
  async function attach(device,opt={}){if(state.connecting)return;state.userDisconnect=false;setBusy(true);try{state.device=device;hookDisconnect(device);savePref({id:device.id,name:device.name||""});$("devInfo").textContent="Thiết bị: "+(device.name||"(không tên)")+" · "+device.id;if(!opt.silent)log("Đã chọn: "+(device.name||device.id));if(device.gatt.connected){try{device.gatt.disconnect();}catch(e){}await sleep(180);}const server=await withTimeout(device.gatt.connect(),12000,"Kết nối GATT");state.server=server;log("Đã vào GATT");const gatt=await withTimeout(discoverGatt(server),8000,"Tìm kênh");state.writeChar=gatt.writeChar;state.notifyChar=gatt.notifyChar;log("Kênh ghi "+gatt.writeChar.uuid+" ["+propsOf(gatt.writeChar)+"]");if(gatt.notifyChar){if(ble.onNotifyBound){try{gatt.notifyChar.removeEventListener("characteristicvaluechanged",ble.onNotifyBound);}catch(e){}}ble.onNotifyBound=onNotify;await withTimeout(gatt.notifyChar.startNotifications(),5000,"Đăng ký nhận");gatt.notifyChar.addEventListener("characteristicvaluechanged",ble.onNotifyBound);log("Kênh nhận "+gatt.notifyChar.uuid);}else log("Máy không có kênh nhận — chỉ gửi một chiều");state.connected=true;state.reconnectTries=0;state.pps="PPS";setBusy(false);render();if(!opt.silent)toast("Đã kết nối");await sleep(200);sendCmd(CMD.QUERY,[0]).catch(()=>{});startPoll();}catch(e){setBusy(false);state.connected=false;render();throw e;}}
  async function requestAndAttach(acceptAll){if(!navigator.bluetooth){toast("Cần Chrome hoặc Edge và HTTPS");log("Trình duyệt không hỗ trợ Web Bluetooth.");return;}const options=acceptAll?{acceptAllDevices:true,optionalServices:OPTIONAL}:{filters:[...PREFIX.map(namePrefix=>({namePrefix})),{services:[ISSC.service]}],optionalServices:OPTIONAL};log(acceptAll?"Hộp thoại: mọi thiết bị":"Hộp thoại: lọc B3PRO / PIVA");try{const device=await navigator.bluetooth.requestDevice(options);await attach(device);}catch(e){if(e.name==="NotFoundError")log("Không chọn máy hoặc không thấy thiết bị.");else if(e.name==="SecurityError")log("Bluetooth web bị chặn. Dùng HTTPS và bấm nút trên trang.");else log("Lỗi: "+e.message);if(!acceptAll&&e.name==="NotFoundError")toast("Không thấy B3PRO — thử Quét tất cả");}}
  async function reconnectLast(){if(state.device){try{await attach(state.device);return;}catch(e){log(e.message);}}if(navigator.bluetooth.getDevices){try{const list=await navigator.bluetooth.getDevices();const meta=loadPref();const hit=list.find(d=>meta.id&&d.id===meta.id)||list.find(d=>/b3|piva/i.test(d.name||""));if(hit){await attach(hit);return;}log("Máy đã cấp quyền: "+(list.map(d=>d.name||d.id).join(", ")||"(trống)"));}catch(e){log("Không đọc được máy đã cấp quyền: "+e.message);}}toast("Chưa có thiết bị đã cấp quyền");}
  async function disconnect(){state.userDisconnect=true;stopPoll();if(ble.reconnectTimer){clearTimeout(ble.reconnectTimer);ble.reconnectTimer=null;}try{state.device?.gatt?.disconnect();}catch(e){}teardownLink();render();toast("Đã ngắt");}
  document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"){if(state.device&&!state.connected&&!state.userDisconnect&&$("autoReconnect").checked)attach(state.device,{silent:true}).catch(()=>{});if(state.connected)startPoll();}else stopPoll();});
  $("autoPoll").addEventListener("change",()=>{savePref({poll:$("autoPoll").checked});state.connected?startPoll():stopPoll();});
  $("autoReconnect").addEventListener("change",()=>savePref({recon:$("autoReconnect").checked}));
  $("codecSel").addEventListener("change",()=>savePref({codec:$("codecSel").value}));
  $("chunkSel").addEventListener("change",()=>savePref({chunk:$("chunkSel").value}));
  function openSheet(kind){const body=$("sheetBody");if(kind==="mode"){body.innerHTML="<h3>Chế độ hiệu năng</h3>"+MODES.map(m=>`<div class="opt${state.mode===m.id?" chon":""}" data-id="${m.id}"><span>${m.name}</span><span>${state.mode===m.id?"✓":""}</span></div>`).join("");body.querySelectorAll(".opt").forEach(el=>el.onclick=()=>{state.mode=+el.dataset.id;sendCmd(CMD.MODE,[state.mode]);render();closeSheet();});}else if(kind==="light"){body.innerHTML="<h3>Hiệu ứng ánh sáng</h3>"+LIGHTS.map(m=>`<div class="opt${state.lightFx===m.id?" chon":""}" data-id="${m.id}"><span>${m.name}</span><span>${state.lightFx===m.id?"✓":""}</span></div>`).join("");body.querySelectorAll(".opt").forEach(el=>el.onclick=()=>{state.lightFx=+el.dataset.id;state.light=true;sendCmd(CMD.LIGHT_FX,[state.lightFx]);render();closeSheet();});}else if(kind==="rage"){body.innerHTML="<h3>Chế độ ép xung</h3><p class='hint'>Tăng công suất và vòng tua. Máy ồn và nóng hơn.</p><div class='row'><button class='btn xanh' id='rageOn'>Bật</button><button class='btn mo' id='rageOff'>Tắt</button></div>";$("rageOn").onclick=()=>{state.rage=true;sendCmd(CMD.RAGE,[1]);render();closeSheet();};$("rageOff").onclick=()=>{state.rage=false;sendCmd(CMD.RAGE,[0]);render();closeSheet();};}else if(kind==="smart"){body.innerHTML="<h3>Điều khiển thông minh</h3><p class='hint'>Giữ nhiệt đầu lạnh theo mục tiêu.</p><label class='hint'>Nhiệt độ mục tiêu (°C)</label><input id='pidTemp' type='number' value='38' min='20' max='55' /><div class='row' style='margin-top:10px'><button class='btn xanh' id='smartOn'>Bật</button><button class='btn mo' id='smartOff'>Tắt</button></div>";$("smartOn").onclick=()=>{const t=Number($("pidTemp").value)||38;state.smart=true;state.mode=3;sendCmd(CMD.SMART,[1,t&255]);sendCmd(CMD.PID_TEMP,[t&255]);render();closeSheet();};$("smartOff").onclick=()=>{state.smart=false;sendCmd(CMD.SMART,[0]);render();closeSheet();};}else if(kind==="protect"){body.innerHTML="<h3>Cơ chế bảo vệ</h3><p class='hint'>Ứng dụng gốc bật bảo vệ khi nhiệt quá cao.</p><div class='opt'><span>Bảo vệ hiệu năng</span><span>✓</span></div><div class='opt'><span>Bảo vệ hiệu ứng đèn</span><span>✓</span></div>";}else if(kind==="fw"){body.innerHTML="<h3>Phiên bản firmware</h3><p>Hiện trên máy: <b>"+state.fw+"</b></p><p class='hint'>Cập nhật firmware OTA không đưa lên bản web này.</p>";}else body.innerHTML="<h3>Bộ điều khiển B3PRO</h3><p class='hint'>Nguồn: ứng dụng Piva 1.7.3</p><p class='hint'>Dịch vụ ISSC UART, dự phòng Nordic UART.</p>";$("sheetBg").classList.add("mo");$("sheet").classList.add("mo");}
  function closeSheet(){$("sheetBg").classList.remove("mo");$("sheet").classList.remove("mo");}
  document.querySelectorAll(".card").forEach(c=>c.addEventListener("click",e=>{if(e.target.closest("button"))return;openSheet(c.dataset.sheet);}));
  $("sheetBg").onclick=closeSheet;
  $("btnMenu").onclick=()=>openSheet("menu");
  $("btnBack").onclick=()=>state.connected?disconnect():requestAndAttach(false);
  $("btnConnect").onclick=()=>requestAndAttach(false);
  $("btnScanAll").onclick=()=>requestAndAttach(true);
  $("btnReconnect").onclick=()=>reconnectLast();
  $("btnDisconnect").onclick=disconnect;
  $("btnQuery").onclick=()=>sendCmd(CMD.QUERY,[0]);
  $("pwrToggle").onclick=e=>{e.stopPropagation();state.power=!state.power;sendCmd(CMD.POWER,[state.power?1:0]);render();};
  $("lightToggle").onclick=e=>{e.stopPropagation();state.light=!state.light;sendCmd(CMD.LIGHT_EN,[state.light?1:0]);render();};
  $("btnSendHex").onclick=()=>{try{writeRaw(parseHex($("hexInput").value));}catch(e){toast(e.message);}};
  $("btnClearLog").onclick=()=>{logEl.textContent="";};
  const pref=loadPref();
  if(pref.codec)$("codecSel").value=pref.codec;
  if(pref.chunk)$("chunkSel").value=pref.chunk;
  if(pref.poll===false)$("autoPoll").checked=false;
  if(pref.recon===false)$("autoReconnect").checked=false;
  render();
  log("Bộ điều khiển PIVA B3PRO sẵn sàng.");
  log("Mã UUID lấy từ ứng dụng Piva 1.7.3.");
})();
